---
title: "Learn Statistical"
author: "Gongcc"
date: "`r Sys.Date()`"
output:
        github_document
editor_options: 
  chunk_output_type: inline
---

## Part One: Perceptron



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

===============Example One===============

```{r}
library(learnML)
X <- iris[1:100,1:2]
y <- iris$Species[1:100]
m <- Perceptron$new(max_iteration = 10000)
m$fit(X, y)
```


```{r}
m$plot()
```

===============Example Two ===============

```{r}
library(learnML)
X <- matrix(c(3, 3, 4, 3, 1, 1), ncol = 2, byrow = TRUE)
y <- c(1, 1, -1)
fit <- Perceptron$new()
fit$fit(X, y, w = c(0,0), b = 0)
```


```{r}
fit$plot()
```

===============Example Three ===============
```{r}
X <- iris[1:100,1:2]
y <- iris$Species[1:100]
set.seed(123)
idx <- sample(100, 50, replace = FALSE)
m <- Perceptron$new()
m$fit(X[idx, ], y[idx])
```

```{r}
m$plot()
```

```{r}
pre <- m$predict(X[-idx,], y[-idx])
# pre
```

```{r}
m$plot(X[-idx, ], y[-idx])
```

===============Example Four ===============

```{r}
X <- iris[1:100,1:4]
y <- iris$Species[1:100]
set.seed(123)
idx <- sample(100, 50, replace = FALSE)
m <- Perceptron$new()
m$fit(X[idx, ], y[idx], seed = 888)
```

```{r}
pre <- m$predict(X[-idx,], y[-idx])
```

```{r}
m$model
```

$`r simsalapar::expr2latex(expr = quote(-0.15 * x[1] + -0.67 * x[2] + 2.08 * x[3] + 0.17 * x[4] + -1.36 == 0))`$

## Part Two: KNN

### kd tree

===============Example One ===============
```{r}
root <- kd.node$new(item = c(2, 4, 5), axis = 2)
root
```

```{r}
root$node_type()
# 0 represents root node
# 1 represents left node
# 2 represents right node
```

`add_child_auto` function add child node, and it will add new child to left or right node by the child node item value.

```{r}
root$add_child_auto(child = kd.node$new(item = c(1,5,5), 
                                        axis = 3))
root$left
root$right
```

```{r}
left <- root$add_child(child = kd.node$new(item = c(3, 2, 4),
                                           axis = 4), 
                       type = 'left')
root$left
```

```{r}
left$parent
```

===============Example Two ===============

```{r}
x <- c(2, 5, 9, 4, 8, 7)
y <- c(3, 4, 6, 7, 1, 2)
tree <- kd.tree$new(matrix(c(x, y ), ncol = 2))
tree
```


```{r}
tree$plot(vertex.label.dist = -3, 
          layout_fun = igraph::layout_as_tree)
```

```{r}
tree$plot(show_id = T, vertex.label.dist = -3)
```

```{r}
tree$df
```

===============Example Three ===============
```{r}
X <- iris[, 1:4]
tree <- kd.tree$new(X)
tree$print()
```

```{r}
tree$plot(show_id = TRUE, node_size = 4, 
          vertex.label.dist = -0.5, edge.arrow.size = .1,
          vertex.label.size = 0.8, show_label = F)
```

```{r}
tree$plot(show_id = TRUE, node_size = 4, 
          vertex.label.dist = -0.5, edge.arrow.size = .1,
          vertex.label.size = 0.8, show_label = F, 
          layout_fun = igraph::layout.fruchterman.reingold)
```

